pbshm/graphcomparison/__init__.py
from pbshm.graphcomparison.routes import *

pbshm/graphcomparison/routes.py
import base64
import io
import math

from flask import Blueprint, render_template, request
import matplotlib.pyplot as plt
import seaborn as sns

from pbshm.authentication import authenticate_request
from pbshm.db import default_collection
from pbshm.timekeeper import nanoseconds_since_epoch_to_datetime
from pbshm.graphcomparison.matrix import ComparisonType, create_similarity_matrix

#Create Blueprint
bp = Blueprint("graphcomparison", __name__, template_folder="templates")

@bp.route("/list")
@authenticate_request("graphcomparison-list")
def list():
	documents = []
	for document in default_collection().aggregate([
		{"$match": {
			"models": {"$exists": True}
		}},
        {"$group":{
            "_id": "$population",
            "structure_names": {"$addToSet": "$name"}
        }},
        {"$project":{
            "_id": 0,
            "population_name": "$_id",
            "structure_names": 1,
        }},
        {"$sort": {"population_name": 1}}
	]):
		documents.append(document)
	return render_template("list-ie-models.html", populations=documents)

@bp.route("/generate")
@bp.route("/generate/<population>")
@authenticate_request("graphcomparison-list-structures")
def generate(population=None):
	match_block = {"models": {"$exists": True}}
	if population is not None:
		match_block["population"] = population
	documents = []
	for document in default_collection().aggregate([
		{"$match": match_block},
		{"$project": {
			"_id": 0,
			"name": 1,
			"population": 1, 
			"timestamp": 1,
			"elements": {"$size": "$models.irreducibleElement.elements"},
			"relationships": {"$size": "$models.irreducibleElement.relationships"}
		}}
	]):
		document["date"] = nanoseconds_since_epoch_to_datetime(document["timestamp"]).strftime("%d/%m/%Y %H:%M:%S")
		documents.append(document)
	return render_template("compare.html", structures=documents, comparison_types=ComparisonType)

@bp.route("/compare", methods=["POST"])
def compare():
	#Acquire Inputs
	form = request.form
	comparison_type_value = form.get("comparison_type")
	name_list = form.getlist("structure_selection")
	name_order = [f"{form.get(f'structure_order_{name}')}:{name}" for name in name_list]
	sorted_name_list = [name.split(':', 1)[-1] for name in sorted(name_order)]
	#Load Models
	structure_list = []
	for name in sorted_name_list:
		for document in default_collection().aggregate([
			{"$match": {
				"name": name
			}},
			{"$project": {
				"_id": 0,
				"name": 1,
				"models": 1
			}},
			{"$limit": 1}
		]):
			structure_list.append(document)
	#Generate Similarity Matrix
	comparison_type = ComparisonType(int(comparison_type_value))
	similarity_matrix, nodes_in_mcs, results_list = create_similarity_matrix(structure_list, structure_list, comparison_type)
	#Prepare Heatmap
	size = math.floor(len(name_list) * 1.15) if len(name_list) > 4 else 7
	fig, ax = plt.subplots(figsize=(size, size), dpi=300)
	sns_ax = sns.heatmap(
		similarity_matrix, annot=True, fmt="0.3f",
		xticklabels=sorted_name_list, yticklabels=sorted_name_list,
		cbar=True, cmap="viridis", ax=ax
	)
	sns_ax.figure.tight_layout()
	#Save to IO stream
	img = io.BytesIO()
	fig.savefig(img, format="png")
	img.seek(0)
	#Render Template
	return render_template("results.html", 
		original_structure_list=sorted_name_list,
		comparison_structure_list=sorted_name_list,
		comparison_type=comparison_type,
		img_result=base64.b64encode(img.read()).decode(),
		jaccard_index_matrix=similarity_matrix,
		nodes_in_mcs_matrix=nodes_in_mcs
	)

pbshm/graphcomparison/templates/compare.html
{% extends 'portal.html'%}
{% block title %}Structures within population{% endblock %}
{% block content %}
<form method="post">
	<div class="d-flex justify-content-end">
		<select name="comparison_type" class="form-control w-50 mr-3">
			{% for comparison in comparison_types %}
			<option value="{{ comparison.value }}">{{ comparison.name }}</option>
			{% endfor %}
		</select>
		<input class="btn btn-primary" type="submit" formaction='{{ url_for("graphcomparison.compare") }}' />
	</div>
	<table class="table table-borderless table-hover mt-2">
		<thead class="bg-info text-white">
			<tr>
				<th scope="col"></th>
				<th scope="col">Name</th>
				<th scope="col">Population</th>
				<th scope="col">Date</th>
				<th scope="col">Elements</th>
				<th scope="col">Relationships</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			{% for model in structures %}
				<tr>
					<td class="p-3">
						<input type="checkbox" name="structure_selection" value='{{ model["name"] }}' />
					</td>
					<td class="font-weight-bold py-3">{{ model["name"] }}</td>
					<td class="font-weight-bold py-3">{{ model["population"] }}</td>
					<td class="font-weight-bold py-3">{{ model["date"] }}</td>
					<td class="font-weight-bold py-3">{{ model["elements"] }}</td>
					<td class="font-weight-bold py-3">{{ model["relationships"] }}</td>
					<td class="p-2">
						{% set structure_index = loop.index %}
						<select name="structure_order_{{ model['name'] }}" class="form-control">
							{% for i in range(structures|length) %}
							<option value="{{ i }}" {{ "selected='selected" if structure_index - 1 == i else 'nope' }}>{{ i + 1 }}</option>
							{% endfor %}
						</select>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</form>
{% endblock %}

pbshm/graphcomparison/templates/list-ie-models.html
{% extends 'portal.html' %}
{% block title %}IE Model Populations{% endblock %}
{% block title_call_to_action %}
    <a href='{{ url_for("graphcomparison.generate") }}' class="btn btn-outline-info">
        Compare All
    </a>
{% endblock %}
{% block content %}
<table class="table table-borderless table-hover mt-2">
    <thead>
        <tr>
            <th scope="col">Population name</th>
            <th scope="col">Structure names</th>
            <th scope="col">Structures</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for item in populations %}
            <tr>
                <td class="font-weight-bold py-3">{{ item["population_name"] }}</td>
                <td class="py-3">
                    {% for name in item["structure_names"] %}{{ "," if loop.index > 1}} {{ name }}{% endfor %}
                </td>
                <td class="py-3">{{ item["structure_names"] | length }}</td>
                <td class="align-middle text-right">
                    <a href='{{ url_for("graphcomparison.generate", population=item["population_name"])}}' class="btn btn-outline-info">
                        Compare
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

pbshm/graphcomparison/templates/results.html
{% extends 'portal.html'%}
{% block title %}Graph comparison results{% endblock %}
{% block content %}
<div class="row">
	<div class="col">
		<p>The structures compared were: {% for name in original_structure_list %}{% if loop.index > 1 %},{% endif %} {{ name }}{% endfor %} using the {{ comparison_type.name }} comparison type.</p>
	</div>
</div>

<div class="card bg-dark text-white mb-3">
	<div class="card-header">Heatmap</div>
	<div class="card-body bg-white text-center">
		<img class="p-4 mx-auto" width="60%" src="data:image/png;base64,{{ img_result }}">
	</div>
</div>

<div class="card bg-success text-white mb-3">
	<div class="card-header">Jaccard Index Matrix</div>
	<div class="card-body bg-white">
		<table class="table table-borderless table-hover table-responsive">
			<thead>
				<tr>
					<th scope="col"></th>
					{% for original_name in original_structure_list %}
						<th scope="col">{{ original_name }}</th>
					{% endfor %}
				</tr>
			</thead>
			<tbody>
				{% for j in range(comparison_structure_list|length) %}
					<tr>
						<td>{{ comparison_structure_list[j] }}</td>
						{% for i in range(original_structure_list|length) %}
							<td>{{ "{:.3f}".format(jaccard_index_matrix[i][j]) }}</td>
						{% endfor %}
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

<div class="card bg-info text-white mb-3">
	<div class="card-header">Nodes in MCS Matrix</div>
	<div class="card-body bg-white">
		<table class="table table-borderless table-hover table-responsive">
			<thead>
				<tr>
					<th scope="col"></th>
					{% for original_name in original_structure_list %}
						<th scope="col">{{ original_name }}</th>
					{% endfor %}
				</tr>
			</thead>
			<tbody>
				{% for j in range(comparison_structure_list|length) %}
					<tr>
						<td>{{ comparison_structure_list[j] }}</td>
						{% for i in range(original_structure_list|length) %}
							<td>{{ nodes_in_mcs_matrix[i][j] }}</td>
						{% endfor %}
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}